### ISSUE TITLE
这个项目如何运行？

### ISSUE THREAD

**Issue by zhangmz0223** [lcw2004/one#17]
我运行了下项目，大概了解项目的
SpringBoot 做接口。前端使用npm run dev运行？
放到服务器的话怎么跑？

**Comment by lcw2004** [comment]
@zhangmz0223 
README.md里面打包那一部分就是说怎么在服务器跑起来的。
简单的来说，服务器端运行的时候，就是把前端编译出来的html等静态资源，放在SpringBoot工程包的resource/static里面，跟后端接口一起运行。

**Comment by zhangmz0223** [comment]
了解。谢谢
