### ISSUE TITLE
配置redis问题

### ISSUE THREAD

**Issue by Zhang-Yida** [lcw2004/one#18]
你好，小菜一枚，想问一下，如何配置Redis？ 后端springboot工程和vue前端工程已经搭建成功，但是现在登录报redis的问题，项目中没有 one-redis

**Comment by lcw2004** [comment]
Redis安装了吧？密码什么的别搞错。

在one\one-main\src\main\resources\application.yml文件最下面就是Redis的配置，现在的配置就是Redis默认的配置
