### ISSUE TITLE
有没有考虑把hibernate替换掉？

### ISSUE THREAD

**Issue by zzvv** [lcw2004/one#2]
例如换成mybatis

**Comment by lcw2004** [comment]
@zzvv 有这个想法，Hibernate的延迟加载在Rest Api里面会多加载很多数据，我也考虑过会将Dao层换成其他的。不过这个计划应该会排在后面一些，会先把前端优化完成再去优化后端。

**Comment by zzvv** [comment]
Nice。我这边如果把数据库跑起来，也可以做一定的辅助。到时候提相关PR，然后你看合并。主要现在跑不起来，很多东西不好开展。
我也又关注到最近好像你比较发力前端这块的东西，把vue做进来了。赞一个，我之前也有这个想法，so我也想加入一起开发，提pr

**Comment by lcw2004** [comment]
@zzvv 
[jeesite.zip](https://github.com/lcw2004/one/files/547989/jeesite.zip)这是我直接mysqldump出来的，我用的是Mysql5.7。
欢迎一起开发，有你帮忙会轻松很多。开发前我们一起沟通下，以免做重复工作。

**Comment by zzvv** [comment]
Hi,我正好打开github在闲逛，在线等回复呢。😄😄。方便留个联系方式吗

**Comment by lcw2004** [comment]
@zzvv QQ：292232611

**Comment by zzvv** [comment]
Nice。我这边如果把数据库跑起来，也可以做一定的辅助。到时候提相关PR，然后你看合并。主要现在跑不起来，很多东西不好开展。 我也又关注到最近好像你比较发力前端这块的东西，把vue做进来了。赞一个，我之前也有这个想法，so我也想加入一起开发，提pr

On 周一, 10月 24, 2016 at 12:54, lcw2004 <notifications@github.com> wrote:
@zzvv [https://github.com/zzvv] 有这个想法，Hibernate的延迟加载在Rest Api里面会多加载很多数据，我也考虑过会将Dao层换成其他的。不过这个计划应该会排在后面一些，会先把前端优化完成再去优化后端。

**Comment by chenglin321** [comment]
@lcw2004 年后了，开始搞起咯。- -

**Comment by lcw2004** [comment]
@chenglin321 在搞前后端分离的Vue单页应用部分，还没合到这个里面来。。

**Comment by ddsdggsg** [comment]
期待吖！

**Comment by heyuanhong08** [comment]
能换成JPA吗

**Comment by lcw2004** [comment]
@heyuanhong08 现在就是jpa的

**Comment by jfoxsolutions** [comment]
Hibernate和MyBatis两个分支都要吧

**Comment by lcw2004** [comment]
@jfoxsolutions 目前我自己的项目中用的是jpa，功能稳定下来前暂时不会考虑改成MyBatis了。
