### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by kakabao** [lcw2004/one#20]
小白一名，项目启动，访问报错This application has no explicit mapping for /error, so you are seeing this as a fallback.有木有详细点的说明，求教。

**Comment by lcw2004** [comment]
@kakabao 你的描述太简单了，看不出来。你把你的执行过程详细描述一下，再把详细的报错信息贴出来才能分析。

**Comment by jfoxsolutions** [comment]
@lcw2004 这个项目是用Eclipse开发的吗？导入Eclipse后执行Maven还是有异常抛出。

**Comment by kakabao** [comment]
我先是maven导入到myeclipse,然后one-main，和workflow中<dependency>
            <groupId>com.lcw.one</groupId>
            <artifactId>one-redis</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>没有这个东西，我注释掉了，然后修改了applicatiion.ypm中数据库驱动信息，main方法启动OneMainApplication,然后local host访问显示This application has no explicit mapping for /error, so you are seeing this as a fallback.哪里错了，求教，没弄过。

**Comment by kakabao** [comment]
@lcw2004

**Comment by lcw2004** [comment]
@jfoxsolutions 不是Eclipse开发的，但是我之前用Eclipse跑过没什么问题。

**Comment by lcw2004** [comment]
1. 导入项目
![image](https://user-images.githubusercontent.com/4246920/33979176-27cae7e6-e0de-11e7-9f7d-3d71f68b6f35.png)
![image](https://user-images.githubusercontent.com/4246920/33979220-5663e332-e0de-11e7-8a3f-efd057859a9c.png)

2. 导入完成之后
![image](https://user-images.githubusercontent.com/4246920/33979343-df2a2aa0-e0de-11e7-9f80-bd254f3c6fd2.png)

3. 配置数据库及Redis
在文件one-main/src/main/resources/application.yml中配置
![image](https://user-images.githubusercontent.com/4246920/33979366-fc285794-e0de-11e7-8210-15b14d74146a.png)
![image](https://user-images.githubusercontent.com/4246920/33979399-216c776a-e0df-11e7-838a-417c8a15f3b3.png)

4. 运行one-main
可以运行起来就可以了。
**注意：这是纯后端，没有界面的，如果在浏览器里面访问会包你贴的错误**
访问 http://127.0.0.1:8080/login.html 是看不到任何东西的

5. 运行one-ui
- 进入one-ui文件夹文件夹
- 依次执行命令`npm install` `npm run dll` `npm run dev`
- 运行起来之后访问 http://127.0.0.1:9000 即可看到前端界面。

**one-ui与后端的交互都是通过上面运行的one-main工程来进行的**

**Comment by lcw2004** [comment]
@kakabao 你是只运行了one-main工程么，one-main工程开发的时候是没有打包界面的，你直接访问就会报上名的错误。你需要运行one-ui工程，在one-ui工程里面与one-main交互。

**Comment by kakabao** [comment]
哦，好的，谢谢

**Comment by kakabao** [comment]
ui工程没起开

**Comment by jiangyun2014** [comment]
@lcw2004 能不能搞个QQ群啊?
