### ISSUE TITLE
请教：登录页可以展现，登录进去是空白的。

### ISSUE THREAD

**Issue by q1991108** [lcw2004/one#23]
如题，首次打开localhost 9000，也是空白的。
后端控制台登录逻辑是没问题的，且有日志输出。
是前端哪块出了问题没跳转呢？

![qq20180110-110011 2x](https://user-images.githubusercontent.com/20982209/34753878-7f59a552-f5f5-11e7-82c1-1ca6e1de6165.jpg)
![qq20180110-110004 2x](https://user-images.githubusercontent.com/20982209/34753871-76cc3d78-f5f5-11e7-9b2c-a95cf13fae8e.jpg)

**Comment by q1991108** [comment]
后端控制台登录逻辑是没问题的，且有日志输出。
是前端哪块出了问题没跳转呢？

**Comment by lcw2004** [comment]
只是首次空白吗？能不看把前端控制台的日志贴出来看一下？

**Comment by q1991108** [comment]
首次空白，然后登录页的url我是手敲的，登录之后又空白了。
主要是在localhost 9000 # 这个地址上是空白的。


还有一个细节是我在执行npm run dev的时候出现找不到 dll/vendor-mainfest.json
后来是我手动 npm run dll 命令之后再执行npm run dev就可以了，不知道和这个有没有关系。
最后打开的页面就是空白的，如题描述。


控制台日志只有这样
![qq20180110-174753 2x](https://user-images.githubusercontent.com/20982209/34766120-67818236-f62e-11e7-946d-65ef6bd44645.jpg)

**Comment by lcw2004** [comment]
> 在执行npm run dev的时候出现找不到 dll/vendor-mainfest.json
后来是我手动 npm run dll 命令之后再执行npm run dev就可以了

这个没影响的，是要先执行npm run dll再执行npm run dev。

**Comment by lcw2004** [comment]
我说的控制台不是这个控制台呢，是浏览器F12之后的控制台。

另外再问几个问题，我没有mac电脑可供测试，不知道是不是跟windows表现一样：
1. 是不是在未登录过的情况下，访问http://127.0.0.1:9000的时候没有自动跳转到http://127.0.0.1:9000/login.html页面？
2. 如果直接访问http://127.0.0.1:9000/login.html页面，输入用户名密码登录之后自动跳转，跳转的页面是否也是空白？

**Comment by q1991108** [comment]
1.是的 2.是空白的

并且我的windows系统下也是这个情况。

以下两张是控制台的图

![1](https://user-images.githubusercontent.com/20982209/34804737-2ebd81c0-f6b5-11e7-924f-812a038b5e4b.jpg)
![2](https://user-images.githubusercontent.com/20982209/34804739-2ef20eea-f6b5-11e7-9701-f38bf0faf163.jpg)

**Comment by lcw2004** [comment]
@q1991108 可以远程看一下吗？

**Comment by lcw2004** [comment]
> ![1](https://user-images.githubusercontent.com/20982209/34805607-f3704c42-f6b9-11e7-9bcb-e17d1fd9cf54.png)

不知道是否是这个报错导致的，你可以改了试一下看看。

文件：one\one-ui\src\common\utils\init\initVeeValidate.js
```
function initVeeValidate () {
  attachIdNumberRule()
  attachMobileRule()
  attachPasswordRule()
  // attachOneAfterRule

  Validator.addLocale(cn)
  const config = {
    locale: 'zh_CN'
  }
  Vue.use(VeeValidate, config)
}
```
把  attachIdNumberRule()、attachMobileRule()、attachPasswordRule()三行代码都屏蔽了再试一下看看。

**Comment by q1991108** [comment]
@lcw2004 还是不行 😂 我微信laiweijia666  QQ751190181

**Comment by lcw2004** [comment]
@q1991108 我已经更新上去了，更新一下即可。是新版本的vee-validate的api有改动，我已经重新适配了。
