### ISSUE TITLE
数据库好像和jeesite原版数据库不能够兼容？

### ISSUE THREAD

**Issue by zzvv** [lcw2004/one#3]
麻烦不知能否把数据库脚本导出一份，谢谢！

**Comment by lcw2004** [comment]
@zzvv 不好意思，最近没看Issues，刚才看到。改了个字段，晚上导一份给你。

**Comment by zzvv** [comment]
感谢。🙏

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.1.25&pv=10.11.6&source=email_footer_2]
On 周一, 10月 24, 2016 at 12:50, lcw2004 <notifications@github.com> wrote:
@zzvv [https://github.com/zzvv] 不好意思，最近没看Issues，刚才看到。改了个字段，晚上导一份给你。
