### ISSUE TITLE
数据库脚本没更新吧？

### ISSUE THREAD

**Issue by zhurui536** [lcw2004/one#30]
数据库脚本没更新吧？项目能跑，但是提示缺少很多表！

**Comment by ronaldoWang** [comment]
请问什么时候更新sql，msg_message和sys_log  没有

**Comment by lcw2004** [comment]
@zhurui536  @ronaldoWang 

更新一下然后执行一下 one\document\one - update - 2018-05-07.sql 脚本就可以了
