### ISSUE TITLE
one-ui一直跑不起

### ISSUE THREAD

**Issue by henry0249** [lcw2004/one#39]
你好，one-ui模块一直跑不起了，我用yarn start或是npm run dev命令都报错。如果有qq可以加一下吗？

**Comment by lcw2004** [comment]
依次运行以下几个命令：
npm install
npm run dll
npm run dev

如果报错，麻烦把报错信息贴到issue里面以下，这样方便分析原因。

**Comment by henry0249** [comment]
按照你的方法，启动了。非常感谢！
