### ISSUE TITLE
WorkFlowApplication启动报错。

### ISSUE THREAD

**Issue by lovefrr** [lcw2004/one#6]
WorkFlowApplication启动报错，更新下代码吧大哥。

**Comment by lcw2004** [comment]
@lovefrr 
workflow是打包在one-main工程里面运行的。
workflow里面的WorkFlowApplication是我用来单独运行workflow工程用的，为了在one-main里面运行，把@SpringBootApplication注释调了，你如果也要单独运行，把注释去掉就可以了。
如果还报错，把错误贴出来我看一下。

**Comment by lovefrr** [comment]
谢谢，我先试一下。

**Comment by lovefrr** [comment]
我签出的dev版本的代码，打开swagger-ui.html会302跳转到login.html页面。

**Comment by lcw2004** [comment]
有登录过滤需要先登录了才能访问这个页面，里面的接口也是一样的，要登录了才能调用。
