### ISSUE TITLE
pom配置文件错误

### ISSUE THREAD

**Issue by summerz1993** [lcw2004/one#7]
根项目pom.xml配置：
`<artifactId>one</artifactId>`
但是其他module引用的是：
`<artifactId>one-extend</artifactId>`
会导致module pom.xml报错，找不到对应的parent

**Comment by lcw2004** [comment]
@summerz1993 麻烦签出下dev分支，已经改了还没合并到master里面

**Comment by summerz1993** [comment]
@lcw2004  OK

**Comment by lcw2004** [comment]
@summerz1993 刚合并过去了。。再更新一下也行。
