### ISSUE TITLE
启动项目之后无法访问login.html

### ISSUE THREAD

**Issue by summerz1993** [lcw2004/one#9]
![image](https://user-images.githubusercontent.com/26996564/27940743-243765c6-62ff-11e7-886b-a5187ca95690.png)

**Comment by lcw2004** [comment]
one-main工程里面是没有这个文件的，你需要编译one-ui，将编译出来的文件拷贝到one-main的resource下面

**Comment by lcw2004** [comment]
你可以看下项目的readme，里面有说明

**Comment by summerz1993** [comment]
好的，谢谢
